# Generated by Django 4.2.2 on 2023-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_up', '0002_alter_userprofile_utility_bill_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='letter_text',
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to='letters/'),
        ),
    ]
